// Author: Timothy Jelinek
// Date: 5/25/2024
// Description: This program generates and prints 25 random numbers between 10 and 100

#include <iostream>
#include <iomanip>
#include <random>
#include <conio.h>

using namespace std;

int main() {
    std::random_device rd; //Used to obtain seed for random number engine
    std::mt19937 gen(rd()); //Standard mersenne_twister_engine seeded with rd()
    std::uniform_real_distribution<> dis(10.0, 100.0);

    for (int n=0; n<25; ++n)
        std::cout <<dis(gen) << ' ' << endl; //Use dis to transform the random unsigned int generated by gen into a double in 10 - 100
        std::cout << '\n';

    cout << "\nPress any key to exit the program.";
    _getch(); // Pause the program so the user can see the output

    return 0;
}
